variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE/renovate:$CI_COMMIT_SHORT_SHA

stages:
  - run

beep-boop:
  image: docker:stable
  stage: run
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_CLI_EXPERIMENTAL: enabled
  services:
    - docker:stable-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - |
      if docker manifest inspect $DOCKER_IMAGE >/dev/null; then
        echo "Image already exists"
      else
        docker build . --tag "$DOCKER_IMAGE" && docker push "$DOCKER_IMAGE"
      fi
    - >
      docker run --rm -t
        -e RENOVATE_TOKEN -e CI_PROJECT_PATH -e CI_PROJECT_URL -e CI_COMMIT_REF_SLUG
        "$DOCKER_IMAGE" bash /workdir/run-renovate.sh
