include:
  - local: .gitlab/ci/infra.renovate-forks.yml

workflow:
  rules:
    # For merge requests, create a pipeline.
    - if: "$CI_MERGE_REQUEST_IID"
    # For `master` branch, create a pipeline (this includes on schedules, pushes, merges, etc.).
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"

default:
  tags:
    - gitlab-org

stages:
  - forks
  - run

.node:
  image: node:18
  stage: run
  before_script:
    - yarn install --frozen-lockfile

execution-plan:
  extends:
    - .node
  needs: []
  variables:
    BASE_IMAGE: $CI_REGISTRY_IMAGE/renovate:$CI_COMMIT_REF_SLUG
  script:
    - node scripts/orchestrate-child-pipeline.mjs --ci-file .gitlab/child-pipeline/generated.yml --docker-files bot_image/docker_files/ --roulette-file renovate/roulette.json
  artifacts:
    paths:
      - renovate/roulette.json
      - bot_image/docker_files/
      - .gitlab/child-pipeline/generated.yml

execute:
  stage: run
  needs:
    - execution-plan
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID
  trigger:
    strategy: depend
    include:
      - local: .gitlab/child-pipeline/entrypoint.yml
      - artifact: .gitlab/child-pipeline/generated.yml
        job: execution-plan

delete-pipelines:
  extends:
    - .node
  resource_group: $CI_COMMIT_REF_SLUG-cleanup
  script:
    - export "GITLAB_TOKEN=$DELETE_PIPELINES_TOKEN"
    - node ./scripts/delete-pipelines.mjs
  rules:
    - if: $DELETE_PIPELINES

.pages:
  extends:
    - .node
  script:
    - curl -O https://gitlab-org.gitlab.io/gitlab-roulette/roulette.json
    - mv roulette.json renovate/
    - node ./scripts/get-renovate-logs.mjs
    - yarn run build
    - cp -r webapp/dist/ public/
    - time find public -type f ! -name "*.bz2" ! -name "*.gz"  -print0 | xargs -0 gzip -f -k
  artifacts:
    paths:
      - public

pages:
  extends:
    - .pages
  publish: public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      # We want to execute this, no matter what. Even if a single job failed.
      when: always
      # Needs the other jobs to be finished
      needs:
        - execute
    # Allow pages job to deploy manually from MRs
    - if: $CI_MERGE_REQUEST_IID
      when: manual
      needs: []

pages-dry-run:
  extends:
    - .pages
  rules:
    - if: $CI_MERGE_REQUEST_IID
      when: "always"
      needs:
        - execute
