variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE/renovate:$CI_COMMIT_SHORT_SHA

stages:
  - build
  - run

build-image:
  image: docker:stable
  stage: build
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_CLI_EXPERIMENTAL: enabled
  services:
    - docker:stable-dind
  script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - |
      if docker manifest inspect $DOCKER_IMAGE >/dev/null; then
        echo "Image already exists"
      else
        docker build . --tag "$DOCKER_IMAGE" && docker push "$DOCKER_IMAGE"
      fi

update-projects:
  image: $DOCKER_IMAGE
  stage: run
  variables:
    GIT_STRATEGY: none
  script:
    - cd /workdir
    - bash ./run-renovate.sh
