variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE/renovate:$CI_COMMIT_REF_SLUG

stages:
  - run

beep-boop:
  tags:
    - gitlab-org-docker
  resource_group: $CI_COMMIT_REF_SLUG
  image: docker:stable
  stage: run
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_CLI_EXPERIMENTAL: enabled
  services:
    - docker:stable-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - |
      BUILD_IMAGE=true
      if docker manifest inspect $DOCKER_IMAGE >/dev/null; then
        echo "Image already exists"
        docker pull $DOCKER_IMAGE
        label=$(docker inspect --format='{{.Config.Labels.commitRef}}' $DOCKER_IMAGE)
        if [ "$label" == "$CI_COMMIT_SHORT_SHA" ]; then
          echo "Image has correct ref, so we skip building"
          BUILD_IMAGE=false
        fi
      fi
      if [ "$BUILD_IMAGE" == "true" ]; then
        echo "Building image"
        docker build . --tag "$DOCKER_IMAGE" --label commitRef=$CI_COMMIT_SHORT_SHA
      fi
    - >-
      docker run --rm -t
      -e RENOVATE_TOKEN -e CI_PROJECT_PATH -e CI_PROJECT_URL -e CI_COMMIT_REF_SLUG
      "$DOCKER_IMAGE" sh /workdir/run-renovate.sh
    - |
      if [ "$BUILD_IMAGE" == "true" ]; then
        echo "Pushing image"
        docker push "$DOCKER_IMAGE"
      fi
