// List of project sorted alphabetically.
projects = [
  "gitlab-org/cluster-integration/auto-build-image",
  "gitlab-org/cluster-integration/auto-deploy-image",
  "gitlab-org/cluster-integration/gitlab-agent",
  "gitlab-org/cluster-integration/helm-install-image",
  "gitlab-org/frontend/pajamas-adoption-scanner",
  "gitlab-org/gitaly",
  "gitlab-org/gitlab",
  "gitlab-org/gitlab-development-kit",
  "gitlab-org/gitlab-docs",
  "gitlab-org/gitlab-elasticsearch-indexer",
  "gitlab-org/gitlab-pages",
  "gitlab-org/gitlab-services/design.gitlab.com",
  "gitlab-org/gitlab-shell",
  "gitlab-org/gitlab-svgs",
  "gitlab-org/gitlab-ui",
  "gitlab-org/gitlab-vscode-extension",
  "gitlab-org/quality/triage-ops",
  "gitlab-org/ruby/gems/gitlab-styles",
  "gitlab-org/security-products/analyzers/gemnasium",
  "gitlab-org/security-products/package-hunter-cli",
  "gitlab-org/status-page",
  "gitlab-org/terraform-images",
  "gitlab-org/terraform-provider-gitlab",
]
