// List of project sorted alphabetically.
projects = [
  { path = "gitlab-org/frontend/playground/accessibility-scanner" },
  { path = "gitlab-org/analytics-section/product-analytics/devkit" },
  { path = "gitlab-org/charts/gitlab-agent", fork_path = "charts-gitlab-agent" },
  { path = "gitlab-org/cluster-integration/auto-build-image" },
  { path = "gitlab-org/cluster-integration/auto-deploy-image" },
  { path = "gitlab-org/cluster-integration/gitlab-agent" },
  { path = "gitlab-org/cluster-integration/gitlab-agent-ci-image" },
  { path = "gitlab-org/cluster-integration/helm-install-image" },
  { path = "gitlab-org/container-registry" },
  { path = "gitlab-org/editor-extensions/gitlab.vim" },
  { path = "gitlab-org/frontend/pajamas-adoption-scanner" },
  { path = "gitlab-org/gitaly" },
  { path = "gitlab-org/gitlab" },
  { path = "gitlab-org/gitlab-development-kit" },
  { path = "gitlab-org/gitlab-docs" },
  { path = "gitlab-org/gitlab-elasticsearch-indexer" },
  { path = "gitlab-org/gitlab-pages" },
  { path = "gitlab-org/gitlab-services/design.gitlab.com" },
  { path = "gitlab-org/gitlab-services/version.gitlab.com" },
  { path = "gitlab-org/gitlab-shell" },
  { path = "gitlab-org/gitlab-svgs" },
  { path = "gitlab-org/gitlab-ui" },
  { path = "gitlab-org/gitlab-vscode-extension" },
  { path = "gitlab-org/gitlab-zoekt-indexer" },
  { path = "gitlab-org/quality/triage-ops" },
  { path = "gitlab-org/ruby/gems/gitlab-styles" },
  { path = "gitlab-org/security-products/analyzers/gemnasium" },
  { path = "gitlab-org/security-products/package-hunter-cli" },
  { path = "gitlab-org/status-page" },
  { path = "gitlab-org/terraform-images" },
  { path = "gitlab-org/terraform-provider-gitlab" },
  { path = "components/opentofu" },
]
