// List of project sorted alphabetically.
projects = [
  { path = "gitlab-com/gl-security/product-security/appsec/tooling/public-mr-confidential-issue-detector" },
  { path = "gitlab-com/gl-security/product-security/appsec/tooling/rotation-management" },
  { path = "gitlab-org/analytics-section/analytics-manager" },
  { path = "gitlab-org/analytics-section/product-analytics/devkit" },
  { path = "gitlab-org/analytics-section/product-analytics/helm-charts", fork_path = "product-analytics-helm-charts" },
  { path = "gitlab-org/api/client-go", fork_path = "api-client-go" },
  { path = "gitlab-org/build/CNG" },
  { path = "gitlab-org/charts/gitlab-agent", fork_path = "charts-gitlab-agent" },
  { path = "gitlab-org/charts/gitlab", fork_path = "charts-gitlab" },
  { path = "gitlab-org/cli" },
  { path = "gitlab-org/cloud-native/gitlab-operator" },
  { path = "gitlab-org/cloud-native/preflight" },
  { path = "gitlab-org/cloud-native/operator" },
  { path = "gitlab-org/cluster-integration/auto-build-image" },
  { path = "gitlab-org/cluster-integration/auto-deploy-image" },
  { path = "gitlab-org/cluster-integration/gitlab-agent" },
  { path = "gitlab-org/cluster-integration/gitlab-agent-ci-image" },
  { path = "gitlab-org/cluster-integration/helm-install-image" },
  { path = "gitlab-org/code-creation/repository-x-ray" },
  { path = "gitlab-org/container-registry" },
  { path = "gitlab-org/developer-relations/contributor-success/contributors-gitlab-com" },
  { path = "gitlab-org/developer-relations/contributor-success/toolbox", fork_path = "contributor-success-toolbox" },
  { path = "gitlab-org/editor-extensions/gitlab.vim" },
  { path = "gitlab-org/editor-extensions/gitlab-lsp" },
  { path = "gitlab-org/editor-extensions/gitlab-jetbrains-plugin" },
  { path = "gitlab-org/frontend/pajamas-adoption-scanner" },
  { path = "gitlab-org/frontend/playground/accessibility-scanner" },
  { path = "gitlab-org/gitaly" },
  { path = "gitlab-org/gitlab" },
  { path = "gitlab-org/gitlab-development-kit" },
  { path = "gitlab-org/gitlab-docs" },
  { path = "gitlab-org/gitlab-elasticsearch-indexer" },
  { path = "gitlab-org/gitlab-environment-toolkit" },
  { path = "gitlab-org/gitlab-pages" },
  { path = "gitlab-org/gitlab-runner" },
  { path = "gitlab-org/gitlab-services/design.gitlab.com" },
  { path = "gitlab-org/gitlab-services/version.gitlab.com" },
  { path = "gitlab-org/gitlab-shell" },
  { path = "gitlab-org/gitlab-svgs" },
  { path = "gitlab-org/gitlab-ui" },
  { path = "gitlab-org/gitlab-vscode-extension" },
  { path = "gitlab-org/gitlab-zoekt-indexer" },
  { path = "gitlab-org/iglu" },
  { path = "gitlab-org/modelops/applied-ml/code-suggestions/ai-assist" },
  { path = "gitlab-org/omnibus-gitlab" },
  { path = "gitlab-org/quality/triage-ops" },
  { path = "gitlab-org/quality/ci_test" },
  { path = "gitlab-org/workspaces/gitlab-workspaces-tools" },
  { path = "gitlab-org/release-cli" },
  { path = "gitlab-org/release-tools" },
  { path = "gitlab-org/rspec_profiling_stats" },
  { path = "gitlab-org/ruby/gems/declarative-policy" },
  { path = "gitlab-org/ruby/gems/gitlab-styles" },
  { path = "gitlab-org/ruby/gems/prometheus-client-mmap" },
  { path = "gitlab-org/security-products/analyzers/gemnasium" },
  { path = "gitlab-org/security-products/package-hunter-cli" },
  { path = "gitlab-org/snowplow-micro-configuration" },
  { path = "gitlab-org/status-page" },
  { path = "gitlab-org/terraform-images" }, // Deprecated
  { path = "gitlab-org/terraform-provider-gitlab" },
  { path = "components/opentofu" },
  { path = "gitlab-org/gitlab-query-language/glql-rust" },
  { path = "gitlab-org/cluster-integration/test-utils/k3s-gitlab-ci", fork_path = "cluster-integration-test-utils-k3s-gitlab-ci" },
  # We cannot fork the following project since they are private
  # See: https://gitlab.com/gitlab-org/frontend/renovate-gitlab-bot/-/issues/12
  # { path = "gitlab-org/analytics-section/product-analytics/analytics-stack" },
  # { path = "gitlab-org/customers-gitlab-com" },
]
